#pragma once

#include "i18n.h"

// Korean (ko) translations.
//
// These translations were generated by a large language model as a starting
// point. Native-speaker contributions are very welcome — please open a PR at
// https://github.com/JonET/monksynth. Every string is indexed by the
// StringId enum in i18n.h; keep entries in the same order. Leave a string
// empty ("") to fall back to the English text in strings_en.h.
//
// All strings are UTF-8.

namespace MonkSynth {
namespace i18n {

constexpr const char *kStringsKo[] = {
    // SetupNeedsTheme
    "MonkSynth의 GUI를 표시하려면 테마가 필요해요.",
    // SetupImportFromClassic1
    "원본 Delay Lama v1.1 플러그인",
    // SetupImportFromClassic2
    "(Windows)에서 클래식 테마를 가져올 수 있습니다.",
    // SetupDownloadFrom
    "아래에서 무료로 다운로드:",
    // SetupThenClick1
    "아래 버튼을 눌러서",
    // SetupThenClick2
    "\"Delay Lama.dll\" 파일을 선택해 주세요.",
    // SetupImportButton
    "클래식 테마 가져오기...",

    // InfoCreatedBy
    "만든 사람: Jonathan Taylor",
    // InfoLicenseHeader
    "라이선스",
    // InfoSourceCodeHeader
    "소스 코드",
    // InfoTagline1
    "Delay Lama에서 영감을 받은 보컬 신디사이저입니다.",
    // InfoTagline2
    "오픈 소스이고 영원히 무료예요.",
    // InfoClose
    "닫기",

    // ContributeHeader
    "나만의 테마 만들기!",
    // ContributeShare
    "커뮤니티에 공유해 보세요",
    // ContributeLookingFor
    "새로운 기본 테마를 찾고 있어요",
    // ContributeOpenFolder
    "테마 폴더 열기",

    // MenuThemePrefix
    "테마: ",
    // MenuLoadTheme
    "테마 불러오기...",
    // MenuImportClassic
    "DLL에서 클래식 테마 가져오기...",
    // MenuOpenFolder
    "테마 폴더 열기",
    // MenuLanguage
    "언어",
    // MenuLanguageAuto
    "자동",
    // MenuPitchBend
    "피치 벤드",
    // MenuPitchBendClassic
    "클래식 (모음)",
    // MenuPitchBendPitch
    "피치",
    // MenuPitchBendBoth
    "둘 다 (피치 + 모음)",
    // MenuPitchBendBothInverted
    "둘 다 (피치 + 반전 모음)",
    // MenuAdvanced
    "고급 매개변수 표시",
    // FileSelectThemeJson
    "테마 폴더에서 theme.json 선택",
    // FileSelectDll
    "Delay Lama DLL 선택",
    // FileExtJson
    "JSON 파일",
    // FileExtDll
    "DLL 파일",

    // ErrCannotOpen
    "선택한 파일을 열 수 없습니다.",
    // ErrUnexpectedSize
    "원본 Delay Lama DLL이 아닌 것 같습니다 "
    "(파일 크기가 예상과 다릅니다).",
    // ErrReadFailed
    "파일을 읽지 못했습니다.",
    // ErrChecksumMismatch
    "원본 Delay Lama DLL이 아닌 것 같습니다 "
    "(체크섬이 일치하지 않습니다).",
    // ErrCreateDir
    "테마 디렉터리를 만들 수 없습니다: ",
    // MsgImportedCount
    "에셋 %d/%d개를 가져왔습니다.",
    // ErrExtractFailed
    "DLL에서 리소스를 추출하지 못했습니다.",
};

static_assert(sizeof(kStringsKo) / sizeof(kStringsKo[0]) ==
                  static_cast<int>(StringId::Count),
              "kStringsKo must have one entry per StringId");

} // namespace i18n
} // namespace MonkSynth
