#pragma once

#include "i18n.h"

// Korean (ko) translations.
//
// These translations were generated by a large language model as a starting
// point. Native-speaker contributions are very welcome — please open a PR at
// https://github.com/JonET/monksynth. Every string is indexed by the
// StringId enum in i18n.h; keep entries in the same order. Leave a string
// empty ("") to fall back to the English text in strings_en.h.
//
// All strings are UTF-8.

namespace MonkSynth {
namespace i18n {

constexpr const char *kStringsKo[] = {
    // SetupNeedsTheme
    "MonkSynth의 GUI를 표시하려면 테마가 필요해요.",
    // SetupImportFromClassic1
    "원본 Delay Lama v1.1 플러그인",
    // SetupImportFromClassic2
    "(Windows)에서 클래식 테마를 가져올 수 있습니다.",
    // SetupDownloadFrom
    "아래에서 무료로 다운로드:",
    // SetupThenClick1
    "\"Delay Lama.dll\" 파일을 여기에 끌어다 놓거나",
    // SetupThenClick2
    "아래 버튼을 눌러 선택해 주세요.",
    // SetupImportButton
    "클래식 테마 가져오기...",
    // SetupOrBuiltIn
    "또는 내장 테마 사용: ",

    // InfoCreatedBy
    "만든 사람: Jonathan Taylor",
    // InfoLicenseHeader
    "라이선스",
    // InfoSourceCodeHeader
    "소스 코드",
    // InfoTagline1
    "Delay Lama에서 영감을 받은 보컬 신디사이저입니다.",
    // InfoTagline2
    "오픈 소스이고 영원히 무료예요.",
    // InfoClose
    "닫기",
    // ThemeInfoAuthorPrefix
    "제작: ",
    // ThemeInfoNoDetails
    "추가 정보가 없습니다.",

    // ContributeHeader
    "나만의 테마 만들기!",
    // ContributeShare
    "커뮤니티에 공유해 보세요",
    // ContributeLookingFor
    "새로운 기본 테마를 찾고 있어요",
    // ContributeOpenFolder
    "테마 폴더 열기",

    // MenuThemePrefix
    "테마: ",
    // MenuLoadTheme
    "테마 불러오기...",
    // MenuImportClassic
    "DLL에서 클래식 테마 가져오기...",
    // MenuOpenFolder
    "테마 폴더 열기",
    // MenuAboutTheme
    "테마 정보...",
    // MenuBuiltInSuffix
    " (내장)",
    // MenuLanguage
    "언어",
    // MenuLanguageAuto
    "자동",
    // MenuPitchBend
    "피치 벤드",
    // MenuPitchBendClassic
    "클래식 (모음)",
    // MenuPitchBendPitch
    "피치",
    // MenuPitchBendBoth
    "둘 다 (피치 + 모음)",
    // MenuPitchBendBothInverted
    "둘 다 (피치 + 반전 모음)",
    // FileSelectThemeJson
    "테마 폴더에서 theme.json 선택",
    // FileSelectDll
    "Delay Lama DLL 선택",
    // FileExtJson
    "JSON 파일",
    // FileExtDll
    "DLL 파일",

    // ErrCannotOpen
    "선택한 파일을 열 수 없습니다",
    // ErrCannotOpenHint
    "DLL을 테마 폴더에 복사한 뒤 다시 가져오기를 누르세요.",
    // ErrUnexpectedSize
    "원본 Delay Lama DLL이 아닌 것 같습니다 "
    "(파일 크기가 예상과 다릅니다).",
    // ErrReadFailed
    "파일을 읽지 못했습니다.",
    // ErrChecksumMismatch
    "원본 Delay Lama DLL이 아닌 것 같습니다 "
    "(체크섬이 일치하지 않습니다).",
    // ErrCreateDir
    "테마 디렉터리를 만들 수 없습니다: ",
    // MsgImportedCount
    "에셋 %d/%d개를 가져왔습니다.",
    // ErrExtractFailed
    "DLL에서 리소스를 추출하지 못했습니다.",

    // MenuBrowseThemes
    "테마 둘러보기...",
    // GalleryTitle
    "테마",
    // GalleryLoading
    "테마를 불러오는 중...",
    // GalleryOffline
    "테마 갤러리에 연결할 수 없습니다.",
    // GalleryRetry
    "다시 시도",
    // GalleryBy
    "제작: ",
    // GalleryPillInUse
    "사용 중",
    // GalleryPillInstalled
    "설치됨",
    // GalleryPillGet
    "받기",
    // GalleryPillUpdate
    "업데이트",
    // GalleryDownload
    "다운로드",
    // GalleryDownloading
    "다운로드 중",
    // GalleryUpdate
    "업데이트",
    // GalleryApply
    "적용",
    // GalleryRemove
    "삭제",
    // GalleryCurrent
    "현재 테마",
    // GalleryMakeOwnTitle
    "나만의 테마 만들기",
    // GalleryMakeOwnBody
    "PNG 8개와 theme.json이면 됩니다. 사양을 읽고 테마 폴더에서 만든 뒤 풀 리퀘스트를 보내면 여기에 추가됩니다.",
    // GalleryThemeSpec
    "테마 사양",
    // GallerySubmit
    "테마 제출",
    // GalleryNoDescription
    "설명이 없습니다.",
    // GalleryDone
    "완료",
    // GalleryFilterAll
    "전체",
    // GalleryFilterAvailable
    "받을 수 있음",
    // GalleryChecking
    "테마 확인 중...",
    // GalleryUpToDate
    "최신 상태입니다",
};

static_assert(sizeof(kStringsKo) / sizeof(kStringsKo[0]) ==
                  static_cast<int>(StringId::Count),
              "kStringsKo must have one entry per StringId");

} // namespace i18n
} // namespace MonkSynth
