#pragma once

#include "i18n.h"

// Japanese (ja) translations.
//
// These translations were generated by a large language model as a starting
// point. Native-speaker contributions are very welcome — please open a PR at
// https://github.com/JonET/monksynth. Every string is indexed by the
// StringId enum in i18n.h; keep entries in the same order. Leave a string
// empty ("") to fall back to the English text in strings_en.h.
//
// All strings are UTF-8.

namespace MonkSynth {
namespace i18n {

constexpr const char *kStringsJa[] = {
    // SetupNeedsTheme
    "MonkSynth を使うにはテーマが必要です。",
    // SetupImportFromClassic1
    "オリジナルの Delay Lama v1.1",
    // SetupImportFromClassic2
    "(Windows 版) からクラシックテーマを読み込めます。",
    // SetupDownloadFrom
    "こちらから無料でダウンロードできます：",
    // SetupThenClick1
    "「Delay Lama.dll」をここにドロップするか、",
    // SetupThenClick2
    "下のボタンで選択してください。",
    // SetupImportButton
    "クラシックテーマを読み込む...",
    // SetupOrBuiltIn
    "または内蔵テーマを使う：",

    // InfoCreatedBy
    "制作：Jonathan Taylor",
    // InfoLicenseHeader
    "ライセンス",
    // InfoSourceCodeHeader
    "ソースコード",
    // InfoTagline1
    "Delay Lama にインスパイアされたボーカルシンセサイザー。",
    // InfoTagline2
    "オープンソースで、ずっと無料です。",
    // InfoClose
    "閉じる",
    // ThemeInfoAuthorPrefix
    "作者：",
    // ThemeInfoNoDetails
    "追加情報はありません。",

    // ContributeHeader
    "オリジナルテーマを作ろう！",
    // ContributeShare
    "コミュニティとシェアしよう",
    // ContributeLookingFor
    "同梱する新しいデフォルトテーマ募集中！",
    // ContributeOpenFolder
    "テーマフォルダを開く",

    // MenuThemePrefix
    "テーマ：",
    // MenuLoadTheme
    "テーマを読み込む...",
    // MenuImportClassic
    "DLL からクラシックテーマを読み込む...",
    // MenuOpenFolder
    "テーマフォルダを開く",
    // MenuAboutTheme
    "テーマについて...",
    // MenuBuiltInSuffix
    "（内蔵）",
    // MenuLanguage
    "言語",
    // MenuLanguageAuto
    "自動",
    // MenuPitchBend
    "ピッチベンド",
    // MenuPitchBendClassic
    "クラシック（母音）",
    // MenuPitchBendPitch
    "ピッチ",
    // MenuPitchBendBoth
    "両方（ピッチ＋母音）",
    // MenuPitchBendBothInverted
    "両方（ピッチ＋母音反転）",
    // FileSelectThemeJson
    "テーマフォルダ内の theme.json を選択",
    // FileSelectDll
    "Delay Lama DLL を選択",
    // FileExtJson
    "JSON ファイル",
    // FileExtDll
    "DLL ファイル",

    // ErrCannotOpen
    "選択したファイルを開けませんでした",
    // ErrCannotOpenHint
    "DLL をテーマフォルダにコピーして、再度お試しください。",
    // ErrUnexpectedSize
    "オリジナルの Delay Lama DLL ではないようです"
    "（ファイルサイズが合いません）。",
    // ErrReadFailed
    "ファイルの読み取りに失敗しました。",
    // ErrChecksumMismatch
    "オリジナルの Delay Lama DLL ではないようです"
    "（チェックサムが一致しません）。",
    // ErrCreateDir
    "テーマディレクトリを作成できませんでした：",
    // MsgImportedCount
    "アセットを %d/%d 個読み込みました。",
    // ErrExtractFailed
    "DLL からリソースを抽出できませんでした。",

    // MenuBrowseThemes
    "テーマを探す...",
    // GalleryTitle
    "テーマ",
    // GalleryLoading
    "テーマを読み込み中...",
    // GalleryOffline
    "テーマギャラリーに接続できません。",
    // GalleryRetry
    "再試行",
    // GalleryBy
    "作: ",
    // GalleryPillInUse
    "使用中",
    // GalleryPillInstalled
    "導入済み",
    // GalleryPillGet
    "入手",
    // GalleryPillUpdate
    "更新",
    // GalleryDownload
    "ダウンロード",
    // GalleryDownloading
    "ダウンロード中",
    // GalleryUpdate
    "更新",
    // GalleryApply
    "適用",
    // GalleryRemove
    "削除",
    // GalleryCurrent
    "現在のテーマ",
    // GalleryMakeOwnTitle
    "自分でテーマを作る",
    // GalleryMakeOwnBody
    "PNG 8 枚と theme.json だけ。仕様を読んでテーマフォルダで作り、プルリクエストを送ればここに追加されます。",
    // GalleryThemeSpec
    "テーマの仕様",
    // GallerySubmit
    "テーマを投稿",
    // GalleryNoDescription
    "説明はありません。",
    // GalleryDone
    "完了",
    // GalleryFilterAll
    "すべて",
    // GalleryFilterAvailable
    "入手可能",
    // GalleryChecking
    "テーマを確認中...",
    // GalleryUpToDate
    "最新です",
};

static_assert(sizeof(kStringsJa) / sizeof(kStringsJa[0]) ==
                  static_cast<int>(StringId::Count),
              "kStringsJa must have one entry per StringId");

} // namespace i18n
} // namespace MonkSynth
