#pragma once

#include "i18n.h"

// Japanese (ja) translations.
//
// These translations were generated by a large language model as a starting
// point. Native-speaker contributions are very welcome — please open a PR at
// https://github.com/JonET/monksynth. Every string is indexed by the
// StringId enum in i18n.h; keep entries in the same order. Leave a string
// empty ("") to fall back to the English text in strings_en.h.
//
// All strings are UTF-8.

namespace MonkSynth {
namespace i18n {

constexpr const char *kStringsJa[] = {
    // SetupNeedsTheme
    "MonkSynth を使うにはテーマが必要です。",
    // SetupImportFromClassic1
    "オリジナルの Delay Lama v1.1",
    // SetupImportFromClassic2
    "(Windows 版) からクラシックテーマを読み込めます。",
    // SetupDownloadFrom
    "こちらから無料でダウンロードできます：",
    // SetupThenClick1
    "下のボタンを押して",
    // SetupThenClick2
    "「Delay Lama.dll」を選択してください。",
    // SetupImportButton
    "クラシックテーマを読み込む...",

    // InfoCreatedBy
    "制作：Jonathan Taylor",
    // InfoLicenseHeader
    "ライセンス",
    // InfoSourceCodeHeader
    "ソースコード",
    // InfoTagline1
    "Delay Lama にインスパイアされたボーカルシンセサイザー。",
    // InfoTagline2
    "オープンソースで、ずっと無料です。",
    // InfoClose
    "閉じる",

    // ContributeHeader
    "オリジナルテーマを作ろう！",
    // ContributeShare
    "コミュニティとシェアしよう",
    // ContributeLookingFor
    "同梱する新しいデフォルトテーマ募集中！",
    // ContributeOpenFolder
    "テーマフォルダを開く",

    // MenuThemePrefix
    "テーマ：",
    // MenuLoadTheme
    "テーマを読み込む...",
    // MenuImportClassic
    "DLL からクラシックテーマを読み込む...",
    // MenuOpenFolder
    "テーマフォルダを開く",
    // MenuLanguage
    "言語",
    // MenuLanguageAuto
    "自動",
    // MenuPitchBend
    "ピッチベンド",
    // MenuPitchBendClassic
    "クラシック（母音）",
    // MenuPitchBendPitch
    "ピッチ",
    // MenuPitchBendBoth
    "両方（ピッチ＋母音）",
    // MenuPitchBendBothInverted
    "両方（ピッチ＋母音反転）",
    // MenuAdvanced
    "詳細パラメータを表示",
    // FileSelectThemeJson
    "テーマフォルダ内の theme.json を選択",
    // FileSelectDll
    "Delay Lama DLL を選択",
    // FileExtJson
    "JSON ファイル",
    // FileExtDll
    "DLL ファイル",

    // ErrCannotOpen
    "選択したファイルを開けませんでした。",
    // ErrUnexpectedSize
    "オリジナルの Delay Lama DLL ではないようです"
    "（ファイルサイズが合いません）。",
    // ErrReadFailed
    "ファイルの読み取りに失敗しました。",
    // ErrChecksumMismatch
    "オリジナルの Delay Lama DLL ではないようです"
    "（チェックサムが一致しません）。",
    // ErrCreateDir
    "テーマディレクトリを作成できませんでした：",
    // MsgImportedCount
    "アセットを %d/%d 個読み込みました。",
    // ErrExtractFailed
    "DLL からリソースを抽出できませんでした。",
};

static_assert(sizeof(kStringsJa) / sizeof(kStringsJa[0]) ==
                  static_cast<int>(StringId::Count),
              "kStringsJa must have one entry per StringId");

} // namespace i18n
} // namespace MonkSynth
